[project]
name = "Quizoboynya"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Quizoboynya developer", email = "you@example.com" }
]

dependencies = [
  "flet==0.28.3",
  "aiofiles"
]

[tool.flet]
org = "com.quizoboynya"
product = "quizoboynya"
company = "Quizoboynya"
copyright = "Copyright (C) 2026 Quizoboynya"

[tool.flet.app]
path = "src"